#%RAML 1.0
title: test3
description: Test3.
mediaType:
  - application/json
version: "v1"
protocols:
  - HTTPS

baseUri: /test/raml/3

uses:
  paths: TestExternalFiles/common-traits3.raml
  uses_traits: TestExternalFiles/common-traits1.raml

is: paths